# -*- coding: utf-8 -*-
"""Titanic.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zcVb6FJ0H9cHdkxcwyne3NeGJrAunWby

Importações
"""

import seaborn as sns
import pandas as pd
import matplotlib.pyplot as plt

titanic = pd.read_csv('titanic.data')

#Tratamento para idades nulas
titanic.fillna({'Age':titanic.Age.mean()} , inplace=True)

#Tratamento na transformação de dados não numéricos em numéricos
titanic['Sex'][titanic['Sex'] == 'male'] = 0
titanic['Sex'][titanic['Sex'] == 'female'] = 1
titanic['Sex'] = pd.to_numeric(titanic['Sex'])

grafico = titanic[['Age','Fare', 'Sex','Survived']].copy()
grafico['Survived'] = grafico['Survived'].apply(str)

sns.pairplot(grafico, hue="Survived")
plt.show()